<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20261006195520 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE abonnement (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, frequence VARCHAR(20) NOT NULL, prix NUMERIC(10, 2) NOT NULL, type_panier_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_351268BB43BBD36C ON abonnement (type_panier_id)');
        $this->addSql('CREATE TABLE client (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, nom VARCHAR(255) NOT NULL, prenom VARCHAR(255) NOT NULL, email VARCHAR(180) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE commande (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, date_debut DATE NOT NULL, statut VARCHAR(20) NOT NULL, client_id INT NOT NULL, abonnement_id INT NOT NULL, point_depot_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_6EEAA67D19EB6921 ON commande (client_id)');
        $this->addSql('CREATE INDEX IDX_6EEAA67DF1D74413 ON commande (abonnement_id)');
        $this->addSql('CREATE INDEX IDX_6EEAA67D17758EBC ON commande (point_depot_id)');
        $this->addSql('CREATE TABLE point_depot (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, nom VARCHAR(255) NOT NULL, adresse VARCHAR(255) NOT NULL, categorie VARCHAR(20) NOT NULL, capacite_max INT NOT NULL, jours_livraison JSON NOT NULL, creneaux_recuperation TEXT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE produit (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, nom VARCHAR(255) NOT NULL, unite VARCHAR(20) NOT NULL, prix_unitaire NUMERIC(10, 2) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE stock (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, mois DATE NOT NULL, quantite NUMERIC(10, 3) NOT NULL, produit_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_4B365660F347EFB ON stock (produit_id)');
        $this->addSql('CREATE TABLE type_panier (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, nom VARCHAR(255) NOT NULL, valeur_cible NUMERIC(10, 2) NOT NULL, actif BOOLEAN NOT NULL, PRIMARY KEY (id))');
        $this->addSql('ALTER TABLE abonnement ADD CONSTRAINT FK_351268BB43BBD36C FOREIGN KEY (type_panier_id) REFERENCES type_panier (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE commande ADD CONSTRAINT FK_6EEAA67D19EB6921 FOREIGN KEY (client_id) REFERENCES client (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE commande ADD CONSTRAINT FK_6EEAA67DF1D74413 FOREIGN KEY (abonnement_id) REFERENCES abonnement (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE commande ADD CONSTRAINT FK_6EEAA67D17758EBC FOREIGN KEY (point_depot_id) REFERENCES point_depot (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE stock ADD CONSTRAINT FK_4B365660F347EFB FOREIGN KEY (produit_id) REFERENCES produit (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE abonnement DROP CONSTRAINT FK_351268BB43BBD36C');
        $this->addSql('ALTER TABLE commande DROP CONSTRAINT FK_6EEAA67D19EB6921');
        $this->addSql('ALTER TABLE commande DROP CONSTRAINT FK_6EEAA67DF1D74413');
        $this->addSql('ALTER TABLE commande DROP CONSTRAINT FK_6EEAA67D17758EBC');
        $this->addSql('ALTER TABLE stock DROP CONSTRAINT FK_4B365660F347EFB');
        $this->addSql('DROP TABLE abonnement');
        $this->addSql('DROP TABLE client');
        $this->addSql('DROP TABLE commande');
        $this->addSql('DROP TABLE point_depot');
        $this->addSql('DROP TABLE produit');
        $this->addSql('DROP TABLE stock');
        $this->addSql('DROP TABLE type_panier');
    }
}
